# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
         # - npm test
          - git push url.ssh://heroku:$53725dd3-1b7c-4437-ab2b-e7aaa0cd5806@git.heroku.com/$zimlancer-backend.git HEAD:master